import importlib.util
import importlib.machinery
import contextlib
import io
import json
import os
import subprocess
import sys
import tempfile
import time
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CLI = ROOT / "bin" / "second-opinion"


def load_cli_module():
    loader = importlib.machinery.SourceFileLoader("second_opinion_cli", str(CLI))
    spec = importlib.util.spec_from_loader("second_opinion_cli", loader)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class RegistryTests(unittest.TestCase):
    def test_required_agents_are_registered(self):
        module = load_cli_module()
        self.assertEqual({"codex", "claude", "opencode", "grok", "antigravity"}, set(module.AGENTS))

    def test_each_skill_mentions_every_target(self):
        module = load_cli_module()
        for agent in module.AGENTS.values():
            skill = module.render_skill(agent)
            self.assertIn(module.MARKER, skill)
            self.assertIn("second-opinion ask auto", skill)
            self.assertIn("--background", skill)
            self.assertIn("second-opinion wait JOB_ID", skill)
            self.assertIn("second-opinion team codex", skill)
            self.assertIn("second-opinion benchmarks --kind models", skill)
            self.assertIn("needs no API key", skill)
            self.assertIn("worker-pool orchestrator, not only a review tool", skill)
            self.assertIn("model agnostic", skill)
            self.assertIn("Prefer capability fit over model branding", skill)
            self.assertIn("Practical routing tips", skill)
            self.assertIn("visual UI, frontend polish", skill)
            self.assertIn("quality depends heavily on the selected model", skill)
            self.assertIn("Optional Goal Mode", skill)
            self.assertIn("Do not use goal mode by default", skill)
            self.assertIn("known native goal command", skill)
            self.assertIn("second-opinion ask auto", skill)
            self.assertIn("--goal", skill)
            self.assertNotIn(f"second-opinion ask {agent.key} --from {agent.key}", skill)
            for key in module.AGENTS:
                self.assertIn(f"`{key}`", skill)

    def test_auto_routing_prefers_expected_surfaces(self):
        module = load_cli_module()
        previous_detect_agents = module.detect_agents
        module.detect_agents = lambda: {
            key: {"detected": True}
            for key in module.AGENTS
        }
        try:
            self.assertEqual(
                module.choose_target("codex", "polish the responsive frontend layout").key,
                "claude",
            )
            self.assertEqual(
                module.choose_target("claude", "fix the backend API auth endpoint tests").key,
                "codex",
            )
            self.assertEqual(
                module.choose_target("codex", "try configured OpenRouter models quickly").key,
                "opencode",
            )
        finally:
            module.detect_agents = previous_detect_agents

    def test_managed_write_skips_unmanaged_existing_files(self):
        module = load_cli_module()
        with tempfile.TemporaryDirectory() as temp:
            path = Path(temp) / "SKILL.md"
            path.write_text("user content", encoding="utf-8")
            status = module.managed_write(path, "generated", force=False, dry_run=False)
            self.assertEqual("skipped-existing", status)
            self.assertEqual("user content", path.read_text(encoding="utf-8"))


class CliCommandTests(unittest.TestCase):
    def run_cli(self, *args, home=None):
        env = os.environ.copy()
        if home:
            env["SECOND_OPINION_HOME"] = str(home)
        return subprocess.run(
            [sys.executable, str(CLI), *args],
            cwd=str(ROOT),
            env=env,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )

    def test_install_all_writes_expected_skill_files(self):
        with tempfile.TemporaryDirectory() as temp:
            home = Path(temp)
            result = self.run_cli("install", "--all", "--yes", home=home)
            self.assertEqual(result.returncode, 0, result.stderr)
            expected = [
                home / ".agents/skills/second-opinion/SKILL.md",
                home / ".claude/skills/second-opinion/SKILL.md",
                home / ".config/opencode/skills/second-opinion/SKILL.md",
                home / ".grok/skills/second-opinion/SKILL.md",
                home / ".gemini/antigravity/skills/second-opinion/SKILL.md",
            ]
            for path in expected:
                self.assertTrue(path.exists(), path)
                self.assertIn("Generated by Second Opinion", path.read_text(encoding="utf-8"))

    def test_status_json_is_valid(self):
        with tempfile.TemporaryDirectory() as temp:
            result = self.run_cli("status", "--json", home=Path(temp))
            self.assertEqual(result.returncode, 0, result.stderr)
            payload = json.loads(result.stdout)
            self.assertEqual(payload["version"], "1.6.0")
            self.assertIn("codex", payload["agents"])
            self.assertIn("antigravity", payload["agents"])

    def test_ask_dry_run_builds_grok_prompt_after_single_flag(self):
        result = self.run_cli("ask", "grok", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("grok", result.stdout)
        self.assertIn("-p", result.stdout)
        self.assertIn("review this", result.stdout)

    def test_codex_dry_run_uses_current_exec_flags(self):
        result = self.run_cli("ask", "codex", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("codex exec", result.stdout)
        self.assertIn("--sandbox workspace-write", result.stdout)
        self.assertNotIn("--ask-for-approval", result.stdout)

    def test_consult_mode_uses_read_only_policies(self):
        result = self.run_cli("ask", "codex", "--mode", "consult", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("--sandbox read-only", result.stdout)

        claude_result = self.run_cli("ask", "claude", "--mode", "consult", "--dry-run", "--", "review this")
        self.assertEqual(claude_result.returncode, 0, claude_result.stderr)
        self.assertIn("--permission-mode plan", claude_result.stdout)

    def test_claude_dry_run_uses_print_mode(self):
        result = self.run_cli("ask", "claude", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("claude -p", result.stdout)
        self.assertIn("--permission-mode auto", result.stdout)

    def test_claude_model_override_is_passed_to_claude(self):
        result = self.run_cli("ask", "claude", "--model", "fable", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("claude -p", result.stdout)
        self.assertIn("--permission-mode auto --model fable", result.stdout)

    def test_claude_dotted_model_ids_are_normalized(self):
        result = self.run_cli("ask", "claude", "--model", "claude-opus-4.8", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("--model claude-opus-4-8", result.stdout)
        self.assertNotIn("--model claude-opus-4.8", result.stdout)

        opencode_result = self.run_cli("ask", "opencode", "--model", "openrouter/anthropic/claude-opus-4.8", "--dry-run", "--", "review this")
        self.assertEqual(opencode_result.returncode, 0, opencode_result.stderr)
        self.assertIn("--model openrouter/anthropic/claude-opus-4.8", opencode_result.stdout)

    def test_goal_prompt_is_opt_in(self):
        result = self.run_cli("ask", "claude", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertNotIn("Opt-in goal mode requested", result.stdout)

        goal_result = self.run_cli(
            "ask",
            "claude",
            "--goal",
            "Finish the migration tests.",
            "--dry-run",
            "--",
            "review this",
        )
        self.assertEqual(goal_result.returncode, 0, goal_result.stderr)
        self.assertIn("Opt-in goal mode requested", goal_result.stdout)
        self.assertIn("Goal: Finish the migration tests.", goal_result.stdout)
        self.assertIn("Native goal command: `/goal Finish the migration tests.`", goal_result.stdout)

        opencode_goal = self.run_cli(
            "ask",
            "opencode",
            "--goal",
            "Explore configured models.",
            "--dry-run",
            "--",
            "review this",
        )
        self.assertEqual(opencode_goal.returncode, 0, opencode_goal.stderr)
        self.assertIn("No native `/goal` command is configured", opencode_goal.stdout)

    def test_antigravity_dry_run_uses_sandbox_and_print_timeout(self):
        result = self.run_cli("ask", "antigravity", "--mode", "consult", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("agy --print", result.stdout)
        self.assertIn("--sandbox --print-timeout 5m0s", result.stdout)
        self.assertIn("review this", result.stdout)
        self.assertLess(result.stdout.index("--print"), result.stdout.index("review this"))
        self.assertLess(result.stdout.index("review this"), result.stdout.index("--sandbox"))

    def test_antigravity_model_override_is_passed_after_prompt(self):
        result = self.run_cli("ask", "antigravity", "--model", "Gemini 3.5 Flash (Low)", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("--model 'Gemini 3.5 Flash (Low)'", result.stdout)
        self.assertLess(result.stdout.index("review this"), result.stdout.index("--model"))

    def test_antigravity_alias_resolves_for_install(self):
        with tempfile.TemporaryDirectory() as temp:
            home = Path(temp)
            result = self.run_cli("install", "--agent", "agy", "--yes", home=home)
            self.assertEqual(result.returncode, 0, result.stderr)
            path = home / ".gemini/antigravity/skills/second-opinion/SKILL.md"
            self.assertTrue(path.exists(), path)

    def test_timeout_flag_is_deprecated_noop(self):
        module = load_cli_module()
        source = CLI.read_text(encoding="utf-8")
        self.assertIn("Deprecated and ignored", source)
        self.assertNotIn("TimeoutExpired", source)
        self.assertNotIn("subprocess.TimeoutExpired", source)
        self.assertEqual(module.VERSION, "1.6.0")

    def test_reasoning_effort_uses_each_native_harness_flag(self):
        cases = (
            ("codex", "--config model_reasoning_effort=xhigh"),
            ("claude", "--effort xhigh"),
            ("opencode", "--variant xhigh"),
            ("grok", "--reasoning-effort xhigh"),
            ("antigravity", "--effort high"),
        )
        for agent, expected in cases:
            with self.subTest(agent=agent):
                effort = "high" if agent == "antigravity" else "xhigh"
                result = self.run_cli(
                    "ask",
                    agent,
                    "--reasoning",
                    effort,
                    "--dry-run",
                    "--",
                    "work on this",
                )
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertIn(expected, result.stdout)

    def test_team_dry_run_builds_five_parallel_role_commands(self):
        result = self.run_cli(
            "team",
            "codex",
            "--count",
            "5",
            "--strategy",
            "balanced",
            "--model",
            "gpt-5.6-luna",
            "--reasoning",
            "xhigh",
            "--manager",
            "none",
            "--dry-run",
            "--",
            "Implement and review this feature",
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stdout.count("# worker "), 5)
        self.assertEqual(result.stdout.count("codex exec"), 5)
        self.assertIn("Specialized role: implementation", result.stdout)
        self.assertIn("Specialized role: independent reviewer", result.stdout)
        self.assertIn("--model gpt-5.6-luna", result.stdout)
        self.assertIn("model_reasoning_effort=xhigh", result.stdout)

    def test_keyless_artificial_analysis_model_parser(self):
        module = load_cli_module()
        row = {
            "id": "1",
            "slug": "worker-model",
            "name": "Worker Model (high)",
            "releaseDate": "2026-08-01",
            "isReasoning": True,
            "intelligenceIndex": 50.0,
            "codingIndex": 72.0,
            "agenticIndex": 47.0,
            "intelligenceIndexTimePerTask": 120.0,
            "intelligenceIndexCostPerTask": {"cost": {"total": 0.125}},
            "timescaleData": {"medianOutputSpeed": 200.0},
            "price1mInputTokens": 0.2,
            "price1mOutputTokens": 1.0,
            "cacheHitPrice": 0.02,
            "creator": {"name": "Example Lab"},
        }
        rsc = '1:{"initialData":' + json.dumps([row], separators=(",", ":")) + "}"
        page = (
            "<html>Artificial Analysis Intelligence Index v4.1"
            "<script>self.__next_f.push("
            + json.dumps([1, rsc], separators=(",", ":"))
            + ")</script></html>"
        )
        payload = module.parse_artificial_analysis_models(page)
        self.assertEqual(payload["index_version"], "4.1")
        model = payload["models"][0]
        self.assertEqual(model["coding_index"], 72.0)
        self.assertEqual(model["agentic_index"], 47.0)
        self.assertEqual(model["cost_per_task_usd"], 0.125)
        self.assertEqual(model["time_per_task_minutes"], 2.0)

    def test_keyless_artificial_analysis_coding_agent_parser(self):
        module = load_cli_module()
        row = {
            "id": "agent-1",
            "agentName": "Codex",
            "displayLabel": "Codex - Worker Model (xhigh)",
            "display": {
                "model": "Worker Model (xhigh)",
                "creator": {"model": "Example Lab"},
            },
            "indexScore": 0.625,
            "mean": {
                "costUsd": 0.25,
                "agentWallTimeSec": 300,
                "steps": 42,
                "totalTokens": 1234,
            },
        }
        rsc = '1:{"benchmarkRows":' + json.dumps([row], separators=(",", ":")) + "}"
        page = "<script>self.__next_f.push(" + json.dumps([1, rsc], separators=(",", ":")) + ")</script>"
        payload = module.parse_artificial_analysis_agents(page)
        agent = payload["agents"][0]
        self.assertEqual(agent["harness"], "Codex")
        self.assertEqual(agent["coding_agent_index"], 62.5)
        self.assertEqual(agent["cost_per_task_usd"], 0.25)
        self.assertEqual(agent["time_per_task_minutes"], 5.0)

    def test_benchmark_loader_needs_no_api_key_and_caches_public_data(self):
        module = load_cli_module()
        row = {
            "slug": "cached-model",
            "name": "Cached Model",
            "intelligenceIndex": 40,
            "codingIndex": 60,
            "agenticIndex": 35,
            "creator": {"name": "Example Lab"},
        }
        rsc = '1:{"initialData":' + json.dumps([row], separators=(",", ":")) + "}"
        page = "<script>self.__next_f.push(" + json.dumps([1, rsc], separators=(",", ":")) + ")</script>"
        with tempfile.TemporaryDirectory() as temp:
            previous_home = os.environ.get("SECOND_OPINION_HOME")
            previous_key = os.environ.pop("AA_API_KEY", None)
            os.environ["SECOND_OPINION_HOME"] = temp
            source = Path(temp) / "public.html"
            source.write_text(page, encoding="utf-8")
            module.ARTIFICIAL_ANALYSIS_MODELS_URL = source.as_uri()
            try:
                fetched = module.load_benchmark_data("models")
                self.assertEqual(fetched["cache"], "refreshed")
                source.unlink()
                cached = module.load_benchmark_data("models", offline=True)
                self.assertEqual(cached["cache"], "hit")
                self.assertEqual(cached["models"][0]["coding_index"], 60)
            finally:
                if previous_home is None:
                    os.environ.pop("SECOND_OPINION_HOME", None)
                else:
                    os.environ["SECOND_OPINION_HOME"] = previous_home
                if previous_key is not None:
                    os.environ["AA_API_KEY"] = previous_key

    def test_obsolete_freedomclaude_flags_are_noops(self):
        with tempfile.TemporaryDirectory() as temp:
            home = Path(temp)
            install_result = self.run_cli(
                "install",
                "--agent",
                "claude",
                "--skip-freedomclaude",
                "--dry-run",
                home=home,
            )
            self.assertEqual(install_result.returncode, 0, install_result.stderr)

            update_result = self.run_cli(
                "update",
                "--base-url",
                ROOT.as_uri(),
                "--path",
                str(CLI),
                "--skip-freedomclaude",
                "--freedomclaude-base-url",
                "https://unused.invalid",
                "--dry-run",
                home=home,
            )
            self.assertEqual(update_result.returncode, 0, update_result.stderr)

    def test_update_replaces_cli_from_base_url(self):
        module = load_cli_module()
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            site_bin = root / "site/bin"
            site_bin.mkdir(parents=True)
            remote_cli = site_bin / "second-opinion"
            remote_cli.write_text(
                "#!/usr/bin/env python3\n"
                '"""Second Opinion CLI."""\n'
                'VERSION = "9.9.9"\n'
                "print('updated second opinion')\n",
                encoding="utf-8",
            )
            target = root / "installed-second-opinion"
            target.write_text(
                "#!/usr/bin/env python3\n"
                '"""Second Opinion CLI."""\n'
                'VERSION = "0.1.0"\n',
                encoding="utf-8",
            )
            target.chmod(0o755)

            output = io.StringIO()
            args = type(
                "UpdateArgs",
                (),
                {
                    "home": str(root / "home"),
                    "path": str(target),
                    "base_url": (root / "site").as_uri(),
                    "force": False,
                    "dry_run": False,
                    "skip_skills": True,
                    "all_skills": False,
                },
            )()
            with contextlib.redirect_stdout(output):
                rc = module.cmd_update(args)
            self.assertEqual(rc, 0)
            self.assertIn("Updated Second Opinion CLI to 9.9.9", output.getvalue())
            self.assertIn('VERSION = "9.9.9"', target.read_text(encoding="utf-8"))

    @unittest.skipIf(
        os.name == "nt",
        "Windows hosted runners cannot safely nest a detached console worker inside unittest.",
    )
    def test_background_job_writes_log_and_metadata(self):
        module = load_cli_module()
        with tempfile.TemporaryDirectory() as temp:
            previous_home = os.environ.get("SECOND_OPINION_HOME")
            os.environ["SECOND_OPINION_HOME"] = temp
            try:
                fake_agent = module.Agent(
                    key="fake",
                    display="Fake Agent",
                    command="fake",
                    skill_path=".fake/SKILL.md",
                    compatibility="fake",
                    aliases=(),
                    strengths="test",
                    consult_args=(),
                    work_args=(),
                )
                rc = module.start_background_job(
                    fake_agent,
                    "consult",
                    [sys.executable, "-c", "print('BACKGROUND_OK')"],
                    Path(temp),
                    "test task",
                    goal="finish test goal",
                )
                self.assertEqual(rc, 0)
                jobs = list((Path(temp) / ".second-opinion/jobs").glob("*.json"))
                self.assertEqual(len(jobs), 1)
                payload = json.loads(jobs[0].read_text(encoding="utf-8"))
                self.assertEqual(payload["goal"], "finish test goal")
                self.assertEqual(payload["schema_version"], 2)
                self.assertEqual(payload["turns"][0]["kind"], "initial")
                log_path = Path(payload["log_path"])
                for _ in range(50):
                    payload = json.loads(jobs[0].read_text(encoding="utf-8"))
                    if (
                        log_path.exists()
                        and "BACKGROUND_OK" in log_path.read_text(encoding="utf-8")
                        and payload.get("state") == "finished"
                        and payload.get("worker_pid") is None
                    ):
                        break
                    time.sleep(0.1)
                self.assertIn("BACKGROUND_OK", log_path.read_text(encoding="utf-8"))
                self.assertEqual(payload["state"], "finished")
                self.assertIsNone(payload["worker_pid"])
                for process in module.DETACHED_PROCESSES:
                    process.wait(timeout=5)
                module.reap_detached_processes()
            finally:
                if previous_home is None:
                    os.environ.pop("SECOND_OPINION_HOME", None)
                else:
                    os.environ["SECOND_OPINION_HOME"] = previous_home

    def test_worker_process_group_options_are_platform_safe(self):
        module = load_cli_module()
        options = module.process_group_options(detach_console=True)
        if os.name == "nt":
            self.assertIn("creationflags", options)
            self.assertTrue(options["creationflags"] & subprocess.CREATE_NEW_PROCESS_GROUP)
            self.assertTrue(options["creationflags"] & subprocess.DETACHED_PROCESS)
        else:
            self.assertEqual(options, {"start_new_session": True})

    def test_steering_queues_a_native_harness_turn_with_changed_model(self):
        module = load_cli_module()
        with tempfile.TemporaryDirectory() as temp:
            previous_home = os.environ.get("SECOND_OPINION_HOME")
            os.environ["SECOND_OPINION_HOME"] = temp
            try:
                job_id = "managed-codex-task"
                meta_path, log_path = module.job_paths(job_id)
                meta_path.parent.mkdir(parents=True)
                log_path.write_text("Initial result\n", encoding="utf-8")
                module.atomic_write_json(
                    meta_path,
                    {
                        "schema_version": 2,
                        "id": job_id,
                        "pid": os.getpid(),
                        "worker_pid": os.getpid(),
                        "agent": "codex",
                        "agent_name": "Codex",
                        "mode": "consult",
                        "cwd": temp,
                        "log_path": str(log_path),
                        "task": "Review the parser",
                        "model": None,
                        "trust": False,
                        "archived": False,
                        "stop_requested": False,
                        "state": "running",
                        "turns": [],
                    },
                )

                module.queue_job_message(job_id, "Focus on malformed input next.")
                module.set_job_model(job_id, "gpt-5.6-codex")
                payload = module.read_job(job_id)
                self.assertEqual(payload["model"], "gpt-5.6-codex")
                self.assertEqual(len(payload["turns"]), 1)
                turn = payload["turns"][0]
                self.assertEqual(turn["kind"], "steer")
                self.assertEqual(turn["message"], "Focus on malformed input next.")
                self.assertIn("--model", turn["command"])
                self.assertIn("gpt-5.6-codex", turn["command"])
                self.assertIn("Initial result", turn["command"][-1])
            finally:
                if previous_home is None:
                    os.environ.pop("SECOND_OPINION_HOME", None)
                else:
                    os.environ["SECOND_OPINION_HOME"] = previous_home

    def test_background_manager_defaults_and_opt_out_flags(self):
        module = load_cli_module()
        previous = os.environ.pop("SECOND_OPINION_MANAGER", None)
        try:
            parser = module.build_parser()
            default_args = parser.parse_args(
                ["ask", "codex", "--background", "--task", "review"]
            )
            terminal_args = parser.parse_args(
                [
                    "ask",
                    "codex",
                    "--background",
                    "--manager",
                    "terminal",
                    "--task",
                    "review",
                ]
            )
            no_window_args = parser.parse_args(
                ["ask", "codex", "--background", "--no-window", "--task", "review"]
            )
            self.assertEqual(default_args.manager, "app")
            self.assertEqual(terminal_args.manager, "terminal")
            self.assertEqual(no_window_args.manager, "none")
        finally:
            if previous is not None:
                os.environ["SECOND_OPINION_MANAGER"] = previous

    def test_manager_environment_default_is_validated(self):
        module = load_cli_module()
        previous = os.environ.get("SECOND_OPINION_MANAGER")
        try:
            os.environ["SECOND_OPINION_MANAGER"] = "terminal"
            self.assertEqual(module.default_manager(), "terminal")
            os.environ["SECOND_OPINION_MANAGER"] = "unexpected"
            self.assertEqual(module.default_manager(), "app")
        finally:
            if previous is None:
                os.environ.pop("SECOND_OPINION_MANAGER", None)
            else:
                os.environ["SECOND_OPINION_MANAGER"] = previous


if __name__ == "__main__":
    unittest.main()
